apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: security-api
  name: security-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: security-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: security-api
    spec:
      containers:
        - image: diegodev41/polyglot-security-api:latest
          name: polyglot-security-api
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: nacos__ServerAddresses__0
              value: "http://nacos-server:8848"
            - name: nacos__Namespace
              value: "polyglot"
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: security-api
  name: security-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: security-api
  type: ClusterIP
status:
  loadBalancer: {}
