apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: transaction-api
  name: transaction-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transaction-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: transaction-api
    spec:
      initContainers:
        - name: wait-for-nacos
          image: busybox:1.28
          command:
            [
              "sh",
              "-c",
              "until nslookup nacos-server; do echo 'Waiting for Nacos DNS'; sleep 2; done; until wget -q --spider http://nacos-server:8848/nacos; do echo 'Waiting for Nacos service'; sleep 2; done",
            ]
      containers:
        - image: diegodev41/polyglot-transaction-api:latest
          name: polyglot-transaction-api
          ports:
            - containerPort: 8080
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"
            - name: nacos__ServerAddresses__0
              value: "http://nacos-server:8848"
            - name: nacos__Namespace
              value: "polyglot"
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: transaction-api
  name: transaction-api
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: transaction-api
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-api-ingress
  annotations:
    konghq.com/strip-path: "true"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /transactions
            pathType: Prefix
            backend:
              service:
                name: transaction-api
                port:
                  number: 8080
